### ISSUE TITLE
Unhandled exception in LiveStreamMonitorService

### ISSUE THREAD

**Issue by no1d** [TwitchLib/TwitchLib.Api#113]
> CoreCLR Version: 4.6.27129.4
Description: The process was terminated due to an unhandled exception.
Exception Info: TwitchLib.Api.Core.Exceptions.InternalServerErrorException: The API answered with a 500 Internal Server Error. Please retry your request
   at TwitchLib.Api.Core.HttpCallHandlers.TwitchHttpClient.HandleWebException(HttpResponseMessage errorResp)
   at TwitchLib.Api.Core.HttpCallHandlers.TwitchHttpClient.GeneralRequest(String url, String method, String payload, ApiVersion api, String clientId, String accessToken)
   at TwitchLib.Api.Core.ApiBase.<>c__DisplayClass13_0`1.<TwitchGetGenericAsync>b__1()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at TwitchLib.Api.Core.ApiBase.<>c__DisplayClass13_0`1.<<TwitchGetGenericAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at TwitchLib.Api.Services.LiveStreamMonitorService.GetLiveStreamersAsync()
   at TwitchLib.Api.Services.LiveStreamMonitorService.UpdateLiveStreamersAsync(Boolean callEvents)
   at TwitchLib.Api.Services.LiveStreamMonitorService.OnServiceTimerTick()
   at TwitchLib.Api.Services.Core.ServiceTimer.TimerElapsedAsync(Object sender, ElapsedEventArgs e)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

I believe exception escapes here
https://github.com/TwitchLib/TwitchLib.Api/blob/5f7bd06f4ec618f4297b4311d5ce6e8ece66c086/TwitchLib.Api/Services/Core/ServiceTimer.cs#L24

From MSDN

> The Timer component catches and suppresses all exceptions thrown by event handlers for the Elapsed event. This behavior is subject to change in future releases of the .NET Framework. Note, however, that this is not true of event handlers that execute asynchronously and include the await operator (in C#) or the Await operator (in Visual Basic). Exceptions thrown in these event handlers are propagated back to the calling thread, as the following example illustrates.

**Comment by Mahsaap** [comment]
Thank you for making issue. I noticed this the other day myself.

**Comment by swiftyspiffy** [comment]
Looking into this.

**Comment by swiftyspiffy** [comment]
I've got a PR here: https://github.com/TwitchLib/TwitchLib.Api/pull/125

This is one of the few ways to resolve this problem. Interested in your thoughts.

Sorry about the large delay in this :(

**Comment by Syzuna** [comment]
The exception is handled in the latest stable release.
Closing :)
