### ISSUE TITLE
WebException: The remote name could not be resolved: 'api.twitch.tv'

### ISSUE THREAD

**Issue by 1jessej** [TwitchLib/TwitchLib.Api#117]
Lately I have been leaving my bot running in debug mode because it tends to crash randomly, and this error has showed up twice now:

System.Net.Http.HttpRequestException
  HResult=0x80131509
  Message=An error occurred while sending the request.
  Source=mscorlib
  StackTrace:
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TwitchLib.Api.Core.Internal.TwitchHttpClientHandler.<SendAsync>d__2.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TwitchLib.Api.Core.HttpCallHandlers.TwitchHttpClient.GeneralRequest(String url, String method, String payload, ApiVersion api, String clientId, String accessToken)
   at TwitchLib.Api.Core.ApiBase.<>c__DisplayClass13_0`1.<TwitchGetGenericAsync>b__1()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TwitchLib.Api.Core.ApiBase.<>c__DisplayClass13_0`1.<<TwitchGetGenericAsync>b__0>d.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TwitchLib.Api.Services.LiveStreamMonitorService.<GetLiveStreamersAsync>d__30.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TwitchLib.Api.Services.LiveStreamMonitorService.<UpdateLiveStreamersAsync>d__26.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TwitchLib.Api.Services.LiveStreamMonitorService.<OnServiceTimerTick>d__27.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TwitchLib.Api.Services.Core.ServiceTimer.<TimerElapsedAsync>d__6.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

Inner Exception 1:
WebException: The remote name could not be resolved: 'api.twitch.tv'

Let me know if you need any more information.

**Comment by swiftyspiffy** [comment]
`WebException: The remote name could not be resolved: 'api.twitch.tv'`

This exception is likely an environment issue more so than a library or Twitch problem. It looks like your environment is unable to connect to the API host (api.twitch.tv) for one reason or another (no internet? dns issue?).

In my opinion, this issue should be handled in your code, as its sort of outside the scope of the library. For that reason, I'm going to close this. Feel free to reopen if you disagree.
