### ISSUE TITLE
Unhandled SSL Exception: TwitchLib.Api.Core.HttpCallHandlers.TwitchHttpClient

### ISSUE THREAD

**Issue by WrithemTwine** [TwitchLib/TwitchLib.Api#188]
While using the "TwitchLib.Api.Services.LiveStreamMonitorService" with a newer .NET 5 update, my apps are starting to crash and there isn't an obvious way to catch it and recover. I'm not seeing exceptions within my own code as a predecessor to this exception. I do notice the call is fine for one cycle (the seconds between checking for live streams) and sometimes crashes on the next cycle or the app runs for hours; in other words a non-deterministic issue. I just tried the app and it crashed in about 10 minutes. I'm not sure if it's a Twitch side connection limiter (stopping connections), a new Twitch update bug, a .NET change with how they handle SSL connections, or something else.

The app context can be found at: https://github.com/WrithemTwine/TwineChatBot/blob/v1.0.2-Beta/MultiUserLiveBot/Clients/TwitchLiveBot.cs
There is a [pre-release v1.0.2 beta binary available](https://github.com/WrithemTwine/TwineChatBot/releases/tag/v1.0.2-Beta), or build your own (there's a signing certificate and you may have to uncheck in the project properties). The app uses "User Scope Settings" to save settings data and an xml for the database.

The stack trace is below from Windows Event Viewer.

Thanks for any help!
-------------------------------------------------------------
CoreCLR Version: 5.0.621.22011
.NET Version: 5.0.6
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Net.InternalException: Exception of type 'System.Net.InternalException' was thrown. -2146892963
   at System.Net.SecurityStatusAdapterPal.GetSecurityStatusPalFromInterop(SECURITY_STATUS win32SecurityStatus, Boolean attachException)
   at System.Net.Security.SslStreamPal.InitializeSecurityContext(SafeFreeCredentials& credentialsHandle, SafeDeleteSslContext& context, String targetName, ReadOnlySpan`1 inputBuffer, Byte[]& outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)
   at System.Net.Security.SecureChannel.GenerateToken(ReadOnlySpan`1 inputBuffer, Byte[]& output)
   at System.Net.Security.SecureChannel.NextMessage(ReadOnlySpan`1 incomingBuffer)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Boolean async, Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at TwitchLib.Api.Core.Internal.TwitchHttpClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at TwitchLib.Api.Core.HttpCallHandlers.TwitchHttpClient.GeneralRequest(String url, String method, String payload, ApiVersion api, String clientId, String accessToken)
   at TwitchLib.Api.Core.ApiBase.<>c__DisplayClass14_0`1.<TwitchGetGenericAsync>b__1()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at TwitchLib.Api.Core.ApiBase.<>c__DisplayClass14_0`1.<<TwitchGetGenericAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at TwitchLib.Api.Services.LiveStreamMonitorService.GetLiveStreamersAsync()
   at TwitchLib.Api.Services.LiveStreamMonitorService.UpdateLiveStreamersAsync(Boolean callEvents)
   at TwitchLib.Api.Services.LiveStreamMonitorService.OnServiceTimerTick()
   at TwitchLib.Api.Services.Core.ServiceTimer.TimerElapsedAsync(Object sender, ElapsedEventArgs e)
   at TwitchLib.Api.Services.Core.ServiceTimer.<.ctor>b__5_0(Object sender, ElapsedEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by LuckyNoS7evin** [comment]
`The SSL connection could not be established`.

This looks like a connection issue from you to twitch, possible DNS, maybe something else. This doesn’t look like a library thing especially as it’s intermittent.

what timing have you got the live monitor set to?

**Comment by WrithemTwine** [comment]
I've had it set to about 5 seconds for quick testing, but it generally sits about 300 seconds. I didn't mention - I've used this code (LiveStreamMonitorService within the TwitchClient) since Feb 22, 2021 without exceptions until the last week. Also, this dropped: https://devblogs.microsoft.com/dotnet/net-may-2021/, and the crashes coincided.

I'm not suggesting this library is directly responsible for the exception, rather .NET is now behaving differently.

Not having the same exceptions with TwitchClient. Haven't fully tested FollowerService.

**Comment by WrithemTwine** [comment]
Am using TwitchLib 3.2.0

**Comment by WrithemTwine** [comment]
Older version was the issue
