### ISSUE TITLE
JsonReaderException: Input string '<float value>' is not a valid integer in API.Helix.Clips.GetClipsAsync()

### ISSUE THREAD

**Issue by xIRoXaSx** [TwitchLib/TwitchLib.Api#194]
Hey there,  
I just found out, that that using the code down below will throw an `JsonReaderException`.  
I'm trying to loop over all clips of multiple channels via `API.Helix.Clips.GetClipsAsync()`.  However, when I try to get the result from `GetClipsAsync()` an JsonReaderException will be thrown.  
  
Tested with:
- Channel having no clips (**no** error)
- Channel having exactly one clip - 80 seconds duration (**no** error)
- Channels having multiple clips including clips with odd duration length (**error**)

Used version: TwitchLib.Api 3.2.3

### Steps to reproduce
1. Find a channel with multiple clips (odd duration length)
2. Set get clips from that specific channel 
```cs
Monitor.Start();
var usersFromMonitor = await API.Helix.Users.GetUsersAsync(logins: Monitor.ChannelsToMonitor);
foreach (var channel in usersFromMonitor.Users) {
    var a = await API.Helix.Clips.GetClipsAsync(broadcasterId: channel.Id);
}
```

### Stack Trace
```
Newtonsoft.Json.JsonReaderException: Input string '17.7' is not a valid integer. Path 'data[1].duration', line 1, position 1257.
   at Newtonsoft.Json.JsonTextReader.ParseReadNumber(ReadType readType, Char firstChar, Int32 initialPosition)
   at Newtonsoft.Json.JsonTextReader.ParseNumber(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadNumberValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsInt32()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at TwitchLib.Api.Core.ApiBase.<>c__DisplayClass16_0`1.<TwitchGetGenericAsync>b__1()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at TwitchLib.Api.Core.ApiBase.<>c__DisplayClass16_0`1.<<TwitchGetGenericAsync>b__0>d.MoveNext()
```

**Comment by Syzuna** [comment]
Hey thanks for reporting that.
Either I was blind or too tired to realizie it but that field should be a float not an integer... or maybe it was changed by Twitch and we didnt notice... will fix that later thx

**Comment by xIRoXaSx** [comment]
> Hey thanks for reporting that.
> Either I was blind or too tired to realizie it but that field should be a float not an integer... or maybe it was changed by Twitch and we didnt notice... will fix that later thx

Thanks a lot for the fast reply and for looking into it! :)

**Comment by Syzuna** [comment]
The wrong type was changed in the dev branch and is now available as prerelease version.
A formal full release will most likely happen later this week or weekend after one of us got time to add some of the new endpoints.
